// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.user_id", "e43969b5-ca2e-4e7d-abb9-935dfa1d80b9");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1609767492);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1607468422);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1609767728);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1609767612);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1609767522);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 10360);
user_pref("browser.cache.disk.capacity", 1024000);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1607468411);
user_pref("browser.laterrun.bookkeeping.sessionCount", 4);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.impressionId", "{57be4e26-d158-4a38-bf6f-0e0c276a4685}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "amazon");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://amazon.com\",\"label\":\"@amazon\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1609767490522");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1609769261522");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1609767466898");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1609789066898");
user_pref("browser.search.region", "FR");
user_pref("browser.search.useDBForOrder", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200720193547");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1609767731");
user_pref("browser.slowStartup.averageTime", 2700);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20200720193547");
user_pref("browser.startup.homepage_override.mstone", "79.0");
user_pref("browser.startup.lastColdStartupCheck", 1609767725);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.tipShownCount.searchTip_onboard", 1);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1607468417495");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "79.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "ac2b07ff3ac54d0eadf6c607e5b6d133");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200720193547");
user_pref("extensions.lastAppVersion", "79.0");
user_pref("extensions.lastPlatformVersion", "79.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"04aef309-4119-42c0-a800-360b5b6d3067\",\"formautofill@mozilla.org\":\"a48c9f11-14c7-4535-b265-0ccfd4c2b382\",\"screenshots@mozilla.org\":\"09e338bc-b991-4207-add3-84cd3f24181a\",\"webcompat-reporter@mozilla.org\":\"f5570e82-3cae-4c15-bbb4-ad2caab65494\",\"webcompat@mozilla.org\":\"358bc074-926e-43f2-9034-733435a49d4d\",\"default-theme@mozilla.org\":\"80d03d59-4cd0-4541-aa9a-058c760c4563\",\"google@search.mozilla.org\":\"5f97e99e-122e-4b6b-b14e-9bafcf517330\",\"amazondotcom@search.mozilla.org\":\"057d59b9-229f-48d9-857c-4e5b10aa5ec3\",\"wikipedia@search.mozilla.org\":\"b1661bcc-40ef-48d3-84d4-3ffb9fd10ba9\",\"bing@search.mozilla.org\":\"f81a7ee0-715b-4525-a024-ec0777346c85\",\"ddg@search.mozilla.org\":\"f61daf63-06bd-4e8c-9a68-3fdfda44cb25\",\"amazon@search.mozilla.org\":\"86ae5e38-53c6-42d2-9477-ff03c6e3e8d1\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "3232ee4d-bc86-4c26-beb2-2abbfee27f78");
user_pref("security.sandbox.plugin.tempDirSuffix", "99529c82-0bc0-4eaf-ab12-73986ba73c98");
user_pref("toolkit.startup.last_success", 1609767723);
user_pref("toolkit.telemetry.cachedClientID", "420908e1-7dad-459a-82a7-064ff266b4e9");
user_pref("toolkit.telemetry.previousBuildID", "20200720193547");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
